version: "3.1"

services:
  be:
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
        - '.:/app'
        - '/app/node_modules'
    ports:
      - 8080:8080
  fe:
    restart: always
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
        - '.:/app'
        - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
        - CHOKIDAR_USEPOLLING=true
    depends_on:
      - be